server:
  port: 14000
spring:
  datasource:
    # 如果需要数据本地化，则改成 file 方式
    # jdbc:h2:file:D:/program/sqlite3/db/testDB;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    url: jdbc:h2:mem:iot-virtual-gateway
    driver-class-name: org.h2.Driver
    username: sa
    password:
#mybatis-plus:
#  configuration:
#  # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jtcl:
  iot:
    platform:
      # IOT平台接口地址
      domain: http://localhost:8080/server-api/
  mqtt:
    enabled: false
    config:
      iot-mqtt: # serverNameXXXXX为服务名，可自由指定
        url: [ "tcp://118.190.215.184:1884" ]
tcp:
  server-port: 30000
logging:
  level:
    io.netty: debug